name 'storj'
maintainer 'Philip Hutchins'
maintainer_email 'philip@storj.io'
license 'AGPL-3.0'
description 'Installs/Configures Storj Services'
long_description 'Installs/Configures Storj Services'
version '0.1.2'

depends 'nvm'
depends 'apt'
depends 'logrotate'
depends 'letsencrypt'
depends 'chef-mongodb'
depends 'nginx', '2.7.6'
depends 'logrotate', '~> 1.9.2'
